[features]
seeds = false
skip-lint = false
[programs.localnet]
poolpals = "A4fkmt1rkdVbcAgAXR3g9d7VYfFdwm6kAQRz6zkk35UY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/andrewhayter/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
